export const EXAMPLE_DATA_FLORIDA = [
  {
    propertyName: "A",
    location: "Pinecrest,FL",
    listedPrice: "$7,995,000",
    suggestedOffer: "$6,795,000",
    bedsBaths: "6 Beds/8 Bath",
    waterfront: "-",
  },
  {
    propertyName: "B",
    location: "Aventura,FL",
    listedPrice: "$2,380,000",
    suggestedOffer: "$2,000,000",
    bedsBaths: "6 Beds/4.5 Bath",
    waterfront: "-",
  },
  {
    propertyName: "C",
    location: "Golden Isles, FL",
    listedPrice: "$4,495,000",
    suggestedOffer: "$3,800,000",
    bedsBaths: "5 Beds/4 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "D",
    location: "Las Olas, FL",
    listedPrice: "$8,495,000",
    suggestedOffer: "$7,000,000",
    bedsBaths: "6 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "E",
    location: "Las Olas, FL",
    listedPrice: "$7,495,000",
    suggestedOffer: "$6,400,000",
    bedsBaths: "6 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "F",
    location: "Coral Ridge, FL",
    listedPrice: "$5,789,000",
    suggestedOffer: "$4,900,000",
    bedsBaths: "4 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "G",
    location: "Coral Ridge, FL",
    listedPrice: "$6,200,000",
    suggestedOffer: "$5,270,000",
    bedsBaths: "5 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "H",
    location: "Coral Ridge, FL",
    listedPrice: "$5,295,000",
    suggestedOffer: "$4,500,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "I",
    location: "Brickell, FL",
    listedPrice: "$5,700,000",
    suggestedOffer: "$4,850,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "J",
    location: "Hollywood, FL",
    listedPrice: "$5,495,000",
    suggestedOffer: "$4,675,000",
    bedsBaths: "5 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "K",
    location: "Fort Lauderdale, FL",
    listedPrice: "$3,500,000",
    suggestedOffer: "$3,000,000",
    bedsBaths: "4 Beds/3.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "L",
    location: "Fort Lauderdale, FL",
    listedPrice: "$4,675,000",
    suggestedOffer: "$4,000,000",
    bedsBaths: "4 Beds/5.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "M",
    location: "West Miami, FL",
    listedPrice: "$1,999,999",
    suggestedOffer: "$1,600,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "N",
    location: "Hollywood Hills, FL",
    listedPrice: "$1,800,000",
    suggestedOffer: "$1,800,000",
    bedsBaths: "8 Beds/7 Bath",
    waterfront: "--",
  },
  {
    propertyName: "O",
    location: "South Miami, FL",
    listedPrice: "$6,498,000",
    suggestedOffer: "$5,500,000",
    bedsBaths: "6 Beds/7 Bath",
    waterfront: "--",
  },
  {
    propertyName: "P",
    location: "Miami Shores, FL",
    listedPrice: "$4,599,000",
    suggestedOffer: "$3,500,000",
    bedsBaths: "6 Beds/5.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "Q",
    location: "Fort Lauderdale, FL",
    listedPrice: "$5,500,000",
    suggestedOffer: "$5,250,000",
    bedsBaths: "7 Beds/9 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "R",
    location: "Fort Lauderdale, FL",
    listedPrice: "$5,850,000",
    suggestedOffer: "$5,275,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "S",
    location: "Fort Lauderdale, FL",
    listedPrice: "$7,800,000",
    suggestedOffer: "$6,500,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "T",
    location: "Fort Lauderdale, FL",
    listedPrice: "$3,700,000",
    suggestedOffer: "$3,000,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "U",
    location: "Coconut Grove, FL",
    listedPrice: "$4,950,000",
    suggestedOffer: "$4,200,000",
    bedsBaths: "5 Beds/7 Bath",
    waterfront: "--",
  },
  {
    propertyName: "V",
    location: "Design District, FL",
    listedPrice: "$1,820,000",
    suggestedOffer: "$1,500,000",
    bedsBaths: "5 Beds/3 Bath",
    waterfront: "--",
  },
  {
    propertyName: "W",
    location: "Design District, FL",
    listedPrice: "$1,950,000",
    suggestedOffer: "$1,600,000",
    bedsBaths: "5 Beds/3 Bath",
    waterfront: "--",
  },
  {
    propertyName: "X",
    location: "Design District, FL",
    listedPrice: "$1,850,000",
    suggestedOffer: "$1,500,000",
    bedsBaths: "4 Beds/3 Bath",
    waterfront: "--",
  },
  {
    propertyName: "Y",
    location: "Design District, FL",
    listedPrice: "$2,800,000",
    suggestedOffer: "$2,500,000",
    bedsBaths: "5 Beds/4 Bath",
    waterfront: "--",
  },
  {
    propertyName: "Z",
    location: "Glenvar Heights, FL",
    listedPrice: "$5,250,000",
    suggestedOffer: "$4,600,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "AA",
    location: "Glenvar Heights, FL",
    listedPrice: "$6,595,000",
    suggestedOffer: "$5,600,000",
    bedsBaths: "7 Beds/6.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "BB",
    location: "Fort Lauderdale, FL",
    listedPrice: "$2,650,000",
    suggestedOffer: "$2,200,000",
    bedsBaths: "4 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "CC",
    location: "Wilton Manners, FL",
    listedPrice: "$2,650,000",
    suggestedOffer: "$2,200,000",
    bedsBaths: "5 Beds/3.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "DD",
    location: "Fort Lauderdale, FL",
    listedPrice: "$3,250,000",
    suggestedOffer: "$2,800,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "EE",
    location: "Brickell, FL",
    listedPrice: "$4,299,000",
    suggestedOffer: "$3,700,000",
    bedsBaths: "4 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "FF",
    location: "Brickell, FL",
    listedPrice: "$2,070,000",
    suggestedOffer: "$1,750,000",
    bedsBaths: "4 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "GG",
    location: "Miami Shores, FL",
    listedPrice: "$4,500,000",
    suggestedOffer: "$3,700,000",
    bedsBaths: "4 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "HH",
    location: "Aventura, FL",
    listedPrice: "$3,090,000",
    suggestedOffer: "$2,700,000",
    bedsBaths: "7 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "II",
    location: "Miami Beach, FL",
    listedPrice: "$14,990,000",
    suggestedOffer: "$5,440,000",
    bedsBaths: "6 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "JJ",
    location: "Pinecrest, FL",
    listedPrice: "$5,950,000",
    suggestedOffer: "$5,100,000",
    bedsBaths: "7 Beds/8 Bath",
    waterfront: "--",
  },
  {
    propertyName: "KK",
    location: "Golden Isles, FL",
    listedPrice: "$7,899,000",
    suggestedOffer: "$6,700,000",
    bedsBaths: "6 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "LL",
    location: "Golden Isles, FL",
    listedPrice: "$6,500,000",
    suggestedOffer: "$5,500,000",
    bedsBaths: "6 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "MM",
    location: "Las Olas, FL",
    listedPrice: "$8,499,000",
    suggestedOffer: "$6,900,000",
    bedsBaths: "6 Beds/8 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "NN",
    location: "Coral Ridge, FL",
    listedPrice: "$6,199,999",
    suggestedOffer: "$5,300,000",
    bedsBaths: "5 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "OO",
    location: "Miami Shores, FL",
    listedPrice: "$2,649,999",
    suggestedOffer: "$2,550,000",
    bedsBaths: "4 Beds/3 Bath",
    waterfront: "--",
  },
  {
    propertyName: "PP",
    location: "Miami Beach, FL",
    listedPrice: "$8,900,000",
    suggestedOffer: "$7,600,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "QQ",
    location: "Venetian Island, FL",
    listedPrice: "$7,999,000",
    suggestedOffer: "$7,000,000",
    bedsBaths: "6 Beds/7.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "RR",
    location: "Hollywood Hills, FL",
    listedPrice: "$1,395,000",
    suggestedOffer: "$1,175,000",
    bedsBaths: "5 Beds/4 Bath",
    waterfront: "--",
  },
  {
    propertyName: "SS",
    location: "Fort Lauderdale, FL",
    listedPrice: "$5,950,000",
    suggestedOffer: "$5,000,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "TT",
    location: "Fort Lauderdale, FL",
    listedPrice: "$7,300,000",
    suggestedOffer: "$6,000,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "UU",
    location: "Brickell, FL",
    listedPrice: "$4,490,000",
    suggestedOffer: "$4,200,000",
    bedsBaths: "7 Beds/7 Bath",
    waterfront: "--",
  },
  {
    propertyName: "VV",
    location: "North Bay Village, FL",
    listedPrice: "$6,499,000",
    suggestedOffer: "$4,500,000",
    bedsBaths: "5 Beds/4 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "WW",
    location: "West Coconut Grove, FL",
    listedPrice: "$5,490,000",
    suggestedOffer: "$4,900,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "XX",
    location: "West Coconut Grove, FL",
    listedPrice: "$4,282,000",
    suggestedOffer: "$3,800,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "YY",
    location: "South Miami, FL",
    listedPrice: "$5,200,000",
    suggestedOffer: "$4,500,000",
    bedsBaths: "7 Beds/7.5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "ZZ",
    location: "Fort Lauderdale, FL",
    listedPrice: "$5,295,000",
    suggestedOffer: "$4,800,000",
    bedsBaths: "5 Beds/4.5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "AAA",
    location: "Fort Lauderdale, FL",
    listedPrice: "$5,295,000",
    suggestedOffer: "$4,800,000",
    bedsBaths: "6 Beds/4.5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "BBB",
    location: "Fort Lauderdale, FL",
    listedPrice: "$6,999,000",
    suggestedOffer: "$6,000,000",
    bedsBaths: "4 Beds/3 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "CCC",
    location: "Miami Shores, FL",
    listedPrice: "$2,465,000",
    suggestedOffer: "$2,000,000",
    bedsBaths: "4 Beds/3 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "DDD",
    location: "Coral Gables, FL",
    listedPrice: "$4,750,000",
    suggestedOffer: "$4,200,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "--",
  },
  {
    propertyName: "EEE",
    location: "Miami, FL",
    listedPrice: "$2,299,000",
    suggestedOffer: "$1,850,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "--",
  },
  {
    propertyName: "FFF",
    location: "Miami, FL",
    listedPrice: "$3,950,000",
    suggestedOffer: "$3,750,000",
    bedsBaths: "5 Beds/4 Bath",
    waterfront: "--",
  },
];

export const EXAMPLE_DATA_ASPEN = [
  {
    propertyName: "A",
    location: "Snowmass Village",
    listedPrice: "$10,987,000",
    suggestedOffer: "$10,750,000",
    bedsBaths: "5 Beds/7 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "B",
    location: "Snowmass Village",
    listedPrice: "$8,250,000",
    suggestedOffer: "$8,000,000",
    bedsBaths: "3 Beds/3 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "C",
    location: "Aspen Core",
    listedPrice: "Off Market",
    suggestedOffer: "$8,000,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "D",
    location: "Aspen Highlands",
    listedPrice: "Off Market",
    suggestedOffer: "$9,000,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "E",
    location: "Snowmass Village",
    listedPrice: "$7,995,000",
    suggestedOffer: "$7,895,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "F",
    location: "Snowmass Village",
    listedPrice: "$2,900,000",
    suggestedOffer: "$2,875,000",
    bedsBaths: "4 Beds/3 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "G",
    location: "Snowmass Village",
    listedPrice: "$7,200,000",
    suggestedOffer: "$7,200,000",
    bedsBaths: "5 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "H",
    location: "Snowmass Village",
    listedPrice: "$9,500,000",
    suggestedOffer: "$9,500,000",
    bedsBaths: "4 Beds/5 Bath",
    waterfront: "Yes",
  },
  {
    propertyName: "I",
    location: "Snowmass Village",
    listedPrice: "$7,250,000",
    suggestedOffer: "$7,250,000",
    bedsBaths: "5 Beds/6 Bath",
    waterfront: "Yes",
  },
];
